import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
//import favicon from "../public/favicon.svg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/assets/icons/favicon.svg"
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" className="h-full w-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-black flex flex-col min-h-full`}
      >
        <Header 
          custom="fixed min-h-[70px] w-full border-b border-b-zinc-300 px-2 bg-white"
          customNav="max-w-[1200px] min-h-[70px] mx-auto flex flex-row items-center gap-5 relative"
        />
        {children}
        <Footer />
      </body>
    </html>
  );
}
